repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.5.0
    hooks:
      - id: check-yaml
      # TODO: enable these later; there are plenty of violating
      #       files that need to be fixed first
      # - id: end-of-file-fixer
      # - id: trailing-whitespace
  - repo: "https://github.com/psf/black"
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
